site_name: ゼロから学ぶ Python
site_description: ゼロから学ぶ Python
site_author: IDA Kenichiro
site_url: http://Nyandaro.github.io/python-book
repo_name: Nyandaro/python-book
repo_url: https://github.com/Nyandaro/python-book
copyright: Copyright &copy 2020 IDA Kenichiro

theme:
  name: material
  palette:
    scheme: preference
    primary: orange
    accent: blue
  font:
    text: Noto Sans
    code: Inconsolata
  language: ja
  logo: img/python.svg
  favicon: img/python.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta

nav:
  - ホーム: index.md
  - 1. Python を始める:
